### PR TITLE
Add support for NAT Gateway for egress

### PR DESCRIPTION
**Pull request by andreadecorte**
First version will use az commands as this is not exposed in azure collection

### CODE REVIEW

**Review by cdoan1 — APPROVED** [review]
LGTM

**Comment by rcarrata** [comment]
@andreadecorte because this repo originally developed (and forked after) in my personal repo, can you please make a PR in order to share this improvement also? Could be awesome to have this feature also reflected there :) We share as we grow :+1:

**Comment by andreadecorte** [comment]
> @andreadecorte because this repo originally developed (and forked after) in my personal repo, can you please make a PR in order to share this improvement also? Could be awesome to have this feature also reflected there :) We share as we grow 👍

https://github.com/rcarrata/ocp4-azure-ipi/pull/3

**Pull request merged**
